### PR TITLE
fixed crash when path contains no slashes.

### PR DESCRIPTION
**Pull request by bahaa-aidi**
used basename() instead of manual parsing.

### CODE REVIEW

**Comment by bahaa-aidi** [comment]
I used strcpy because basename() may change the passed argument.
Which would cause the next fopen(path, "rb"); to open the wrong file.

**Comment by jwilberding** [comment]
Ahh, that is annoying, I just updated the code then to do this:

filename = (char *)path;
filename = basename(filename);

**Comment by bahaa-aidi** [comment]
That won't work, because filename points to same memory as path, so any change that basename() does to filename
will change path and fopen() will fail.

**Comment by jwilberding** [comment]
Good point, I will just move it to after fopen then. We won't need path again after that.

**Pull request closed without merging**
