### PR TITLE
Added the GNU GPLv3 license to the project

### PR DESCRIPTION
**Pull request by ragkousism**
Added the GNU GPLv3 license to the project ,closing issue #18.

### CODE REVIEW

**Comment by jwilberding** [comment]
@Phant0mas This is great, but is it possible to put the file in the root folder and not in it's own folder?

**Comment by ragkousism** [comment]
Of course

**Comment by jwilberding** [comment]
Sorry to nitpick! But could you please squash the commits so there is only one commit? As it stands now, the first commit creates LICENSE/LICENSE and the second commit moves it to -> LICENSE, it'd be better to just have one commit that creates the LICENSE file in the root directory, along with adding the license line to the source code.

Thanks!

**Comment by ragkousism** [comment]
You are right ,sorry I am still learning git , I will fix it as soon as possible

**Comment by jwilberding** [comment]
No worries, if you need help, just let me know, I can walk you through it :)

**Comment by ragkousism** [comment]
I squashed the two commits into one, I think it's ready now

**Comment by ragkousism** [comment]
@jwilberding have you seen the fixed commit dude?

**Comment by jwilberding** [comment]
@Phant0mas Oops, sorry, I do now. Thanks for doing that!

**Pull request merged**
